# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MENU_interfaz0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import*

import time
from Adafruit_IO import Client


ADAFRUIT_IO_USERNAME = "Angie2002"
ADAFRUIT_IO_KEY = "aio_ToIi48ubNUb8NL1bC1I67jXVt7xe"

aio = Client(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 425)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QRect(60, 60, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(150, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QRect(250, 60, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalSlider = QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QRect(70, 150, 160, 22))
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QRect(70, 190, 160, 22))
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QRect(70, 280, 160, 22))
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 =QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QRect(70, 350, 160, 22))
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setOrientation(Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(70, 120, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(70, 250, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(60, 320, 55, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 =QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QRect(260, 260, 101, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QRect(260, 230, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(260, 210, 55, 17))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 404, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox.setItemText(11, _translate("MainWindow", "COM11"))
        self.pushButton.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_2.setText(_translate("MainWindow", "CLOSE"))
        self.label.setText(_translate("MainWindow", "P1"))
        self.label_2.setText(_translate("MainWindow", "P2"))
        self.label_3.setText(_translate("MainWindow", "P3"))
        self.pushButton_3.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MANUAL"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EPROM"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "SERIAL"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "ADAFRUIT"))
        self.label_4.setText(_translate("MainWindow", "MODOS"))
